services:

  postgres:
    image: postgres:15
    container_name: books_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - books_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: books_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - books_network

  app:
    build: .
    container_name: books_app
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - books_network
    command: echo "App ready"

  streamlit:
    build: .
    container_name: books_streamlit
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - books_network
    command: streamlit run dashboard.py --server.address=0.0.0.0 --server.port=8501

volumes:
  postgres_data:
  pgadmin_data:

networks:
  books_network:
    driver: bridge